### ISSUE TITLE
Redefine system images tag/push/mirror process

### ISSUE THREAD

**Issue by alena1108** [rancher/tasks#141]
- [ ] Introduce a file containing all the images and their original/target tag in kontainer-driver-metadata, types, system-catalog repos. See if dedicated CI flow repo for publishing images makes sense. Automate the process of checking the image existence in the file before accepting chars/metadata changes referencing the image https://github.com/rancher/rancher/issues/21221

- [ ] Add scripts and Drone logic for tagging and pushing images and corresponding Manifests https://github.com/rancher/rancher/issues/22132

**Comment by cbron** [comment]
This is sort of finished by image-mirror, up to team 2 how they want to automate KDM stuff.
