### ISSUE TITLE
Update Rancher Kustomize urls to point to upstream images

### ISSUE THREAD

**Issue by cbron** [rancher/tasks#158]
* https://github.com/rancher/rancher/blob/cc64610a841616c64fd3343fb5093d6be0200d72/package/Dockerfile#L73
* https://github.com/rancher/rancher/blob/cc64610a841616c64fd3343fb5093d6be0200d72/Dockerfile.dapper#L58

~Both of those need to move to a fork in Rancher org. Alternatively we could look into using: 
https://github.com/raspbernetes/multi-arch-images~

Support for arm was added in this release https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.8 - 

Upgrade the rancher kustomize version to this newest version and ensure all kustomize images are pointing to the upstream  kustomize repo. This will remove the dependency on dev's repo and will no longer need to be moved into the rancher org. 

Clean up https://github.com/rancher/kustomizebuild as it is not longer needed.

**Comment by brendarearden** [comment]
https://github.com/rancher/rancher/pull/32720 this was also updated here

**Comment by cbron** [comment]
~@brendarearden what else is needed to close this now ?~
We still need to backport.
