### ISSUE TITLE
Add Readiness Probe endpoint to agents

### ISSUE THREAD

**Issue by superseb** [rancher/tasks#16]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Currently when an agent is started, there is no indication if it's ready/successful. The log can show bad handshake/certificate signed by unknown authority but there is no indication anything is wrong in API output.

If we can implement a check for the agent to mark it as ready, that would help indicating it has successfully connected. Adding a Liveness Probe way might be too tricky to do.

**Comment by mitchellmaler** [comment]
When we have done some maintenance on Rancher server (small downtime) we have had instances where the agent doesn't reconnect (maybe just not fast enough) so we have to restart it. From the logs I can see it lost connection. I would expect a health check to report to kubernetes that it is not healthy anymore so it could restart it automatically.
