### ISSUE TITLE
[Backup Restore Operator] Move CRs out of the crds directory

### ISSUE THREAD

**Issue by nickgerace** [rancher/tasks#172]
There are CRs in the CRDs directory, which can be confusing to new users. We should consider moving these to their own `cr/` directory.

Repository: https://github.com/rancher/backup-restore-operator/tree/master/crds

**Comment by cbron** [comment]
Do we understand why Rajashree put them in there in the first place ? Might be related to CRD chart not being uninstalled even when the operator is.

**Comment by nickgerace** [comment]
I researched the repository and I cannot find a strong reason that it's in the CRD directory.

**Comment by nickgerace** [comment]
It was "only being maintained during the initial development/testing" of the backup-restore-operator. https://github.com/rancher/backup-restore-operator/pull/74#issuecomment-790028095

**Comment by nickgerace** [comment]
Completed by: https://github.com/rancher/backup-restore-operator/issues/78
