### ISSUE TITLE
Fix Dev Cycle for Install Docker Scripts

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/tasks#187]
We need to look at the dev cycle for the docker scripts install, because currently the only way we can test the docker release is after it has been released to production, which is not ideal for QA.

**Comment by vincent99** [comment]
They're static files, you can load them from anywhere.  Or separate uploading a new x.y.z.sh from updating the x.y.sh symlink to point to the new ".z" version until after its been tested.

**Comment by superseb** [comment]
A way to address this is described in https://github.com/rancher/install-docker/pull/62

**Comment by superseb** [comment]
https://github.com/rancher/install-docker/pull/62 is merged
