### ISSUE TITLE
Ensure that all non-mirrored DockerHub Rancher images use RCs instead of multiple tags

### ISSUE THREAD

**Issue by nickgerace** [rancher/tasks#197]
Currently, images, such as `rancher/gitjob` and `rancher/fluentd` do not use RCs. Tags are incremented by patch release until one is selected for inclusion in their chart/app/service. We should _first_ enable easy dev RC creation/chart inclusion and easy QA RC testing, and then enforce using RCs where they make sense.

cc: @cbron for the original idea

**Comment by cbron** [comment]
Whats the technical goal of this issue specifically, is it to scan for non-rc images ? Or scan for rc images pre-release.

**Comment by nickgerace** [comment]
@cbron This is more of a "process" goal. I think technical solutions may be a misuse of time, since we would have to validate that non-RC tags are only created once between releases.

**Comment by nickgerace** [comment]
Closing this issue after speaking to @cbron since it is beyond the scope of this repo

**Comment by cbron** [comment]
@nickgerace can you add to release checklist
