### ISSUE TITLE
Replace install.goreleaser.com for installing golangci-lint

### ISSUE THREAD

**Issue by superseb** [rancher/tasks#203]
The subdomain `install.goreleaser.com` is gone and this way of installing is deprecated. It should be replaced with;

```
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.46.2
```

Affected repositories:

## area1
- [x] rancher/cli `Dockerfile.dapper`
- [x] rancher/dapper `Dockerfile.dapper`
- [x] rancher/kube-api-auth `Dockerfile.dapper`
- [ ] rancher/norman `Dockerfile.dapper`
- [x] rancher/shell `Dockerfile.dapper`

## area2
- [ ] rancher/aks-operator `Dockerfile.dapper`
- [ ] rancher/channelserver `Dockerfile.dapper`
- [ ] rancher/eks-operator `Dockerfile.dapper`
- [ ] rancher/gke-operator `Dockerfile.dapper`
- [ ] rancher/kontainer-driver-metadata `Dockerfile.dapper`
- [ ] rancher/rke `Dockerfile.dapper`
- [ ] rancher/system-upgrade-controller `Dockerfile.dapper`
- [ ] rancher/system-agent `Dockerfile.dapper`

## area3
- [ ] rancher/charts-build-scripts `Dockerfile.dapper`
- [ ] rancher/cis-operator `Dockerfile.dapper`
- [ ] rancher/fluentd `Dockerfile.dapper`
- [ ] rancher/prometheus-federator `Dockerfile.dapper`
- [ ] rancher/webhook-receiver `Dockerfile.dapper`

## harvester
- [ ] rancher/harvester-server `Dockerfile.dapper`

## Misc
- [ ] rancher/config-modifier `Dockerfile.dapper`
- [ ] rancher/gitjob `Dockerfile.dapper`
- [ ] rancher/gitwatcher `Dockerfile.dapper`
- [x] rancher/go-skel `Dockerfile.dapper`
- [ ] rancher/helm-locker `Dockerfile.dapper`
- [ ] rancher/helm-project-operator `Dockerfile.dapper`
- [ ] rancher/k3os `Dockerfile.dapper`
- [ ] rancher/local-path-provisioner `Dockerfile.dapper`
- [ ] rancher/migration-agent `Dockerfile.dapper`
- [ ] rancher/os2 `Dockerfile.dapper`
~~-  rancher/wrangler-api `Dockerfile.dapper`~~
- [ ] rancher/terraform-controller `Dockerfile.dapper`

Not doing:
* rancher/rancherd `Dockerfile.dapper`
* rancher/rio `Dockerfile.dapper`
* rancher/rio-autoscaler `Dockerfile.dapper`
* rancher/types `Dockerfile.dapper`

PR for go-skel: https://github.com/rancher/go-skel/pull/41

**Comment by macedogm** [comment]
Fixed:
- [x] [rancher/webhook-receiver](https://github.com/rancher/webhook-receiver/pull/11/)
- [x] [rancher/gitjob](https://github.com/rancher/gitjob/pull/50)

**Comment by steffantucker** [comment]
Fixed:
- [x] [rancher/dapper](https://github.com/rancher/dapper/pull/110)
