### ISSUE TITLE
Save outputs of Rancher logs externally when tests fail to improve build speed. 

### ISSUE THREAD

**Issue by maggieliu** [rancher/tasks#44]
* Save outputs of Rancher logs externally when tests fail to improve build speed.

**Comment by cbron** [comment]
Is this done technically since we just ended up removing them @dramich  ?

**Comment by dramich** [comment]
Yeah, I think it's agreed that rancher logs from tests just aren't useful.

**Comment by cbron** [comment]
K closing for now, until we come across a scenario where we need that data and want to export to view it.
