### ISSUE TITLE
Charts Integration testing framework

### ISSUE THREAD

**Issue by maggieliu** [rancher/tasks#9]
Need integration testing framework for the rancher/charts repo and add it into the CI pipepline
Current plane is to look into helm test
* official docs: https://helm.sh/docs/topics/chart_tests/
* base example: https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/tests/test-mariadb-connection.yaml

https://github.com/rancher/rancher/issues/28630

**Comment by cbron** [comment]
This should include a generic check on the chart (or all charts) that any images defined should be defined correctly and start with `rancher/`, as that will break rancher master builds as soon as we merge the chart.
Also any other base checks like that we can think of. Like running `helm template` on the chart or something to ensure its valid.
